# Generated by Django 4.0.5 on 2022-08-09 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensajeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={},
        ),
        migrations.DeleteModel(
            name='Hilo',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='receptor',
            field=models.ManyToManyField(to='mensajeria.receptor'),
        ),
    ]
