# Generated by Django 4.0.5 on 2022-08-10 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensajeria', '0004_mensajes_usuario_delete_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Msj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=75)),
                ('destinatario', models.CharField(max_length=25)),
                ('cuerpo', models.TextField()),
                ('fecha_enviado', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='destinatario',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
