# Generated by Django 4.0.5 on 2022-08-10 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0005_msj_alter_mensajes_destinatario_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensajes',
        ),
    ]
