# Generated by Django 4.0.5 on 2022-07-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nacimiento',
            field=models.CharField(max_length=50),
        ),
    ]
