# Generated by Django 4.0.5 on 2022-07-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0003_alter_usuario_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nacimiento',
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
