# Generated by Django 4.0.5 on 2022-08-01 01:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0006_categoria_posteo_comentarios'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='posteo',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='posteo',
            name='slug',
        ),
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
