# Generated by Django 4.0.5 on 2022-08-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0007_alter_posteo_managers_remove_posteo_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
