# Generated by Django 4.0.5 on 2022-08-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0008_remove_posteo_descripcion_alter_posteo_contenido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=models.CharField(max_length=500),
        ),
    ]
