# Generated by Django 4.0.5 on 2022-08-01 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppDiario', '0009_alter_posteo_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
