# Generated by Django 4.0.5 on 2022-08-01 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppDiario', '0011_alter_posteo_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
