# Generated by Django 4.0.5 on 2022-08-03 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0014_posteodeportes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosteoEspectaculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('contenido', models.TextField()),
                ('publicado', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
