# Generated by Django 4.0.5 on 2022-08-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0017_imagen_posteodeportes_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteodeportes',
            name='foto',
        ),
    ]
