# Generated by Django 4.0.5 on 2022-08-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0018_remove_posteodeportes_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteodeportes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
