# Generated by Django 4.0.5 on 2022-08-06 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0019_posteodeportes_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='posteo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppDiario.posteodeportes'),
        ),
    ]
