# Generated by Django 4.0.5 on 2022-08-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0020_imagen_posteo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='posteo',
        ),
        migrations.AlterField(
            model_name='posteodeportes',
            name='foto',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
