# Generated by Django 4.0.5 on 2022-08-06 22:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0021_remove_imagen_posteo_alter_posteodeportes_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteodeportes',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
