# Generated by Django 4.0.5 on 2022-08-06 22:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0023_alter_posteodeportes_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteodeportes',
            name='titulo',
            field=ckeditor.fields.RichTextField(max_length=150),
        ),
    ]
