# Generated by Django 4.0.5 on 2022-08-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0024_alter_posteodeportes_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteodeportes',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
