# Generated by Django 4.0.5 on 2022-08-06 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0025_alter_posteodeportes_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteodeportes',
            name='foto',
        ),
    ]
