# Generated by Django 4.0.5 on 2022-08-08 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDiario', '0027_posteoeconomia_autor_posteoespectaculos_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteodeportes',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
